In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/fitness_tracker.csv")
df

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours
0,FIT1000,Suresh,NaN,Female,15257.0,300.0,97.0,01-01-2022,NaN,7.8
1,FIT1001,Priya,30.0,Male,1570.0,119.0,NaN,02-01-2022,179.0,3.8
2,FIT1002,Arun,49.0,Male,15594.0,206.0,33.0,03-01-2022,133.0,4.0
3,FIT1003,Vikram,39.0,Female,4085.0,NaN,117.0,04-01-2022,95.0,NaN
4,FIT1004,Divya,23.0,Male,14407.0,969.0,56.0,05-01-2022,84.0,NaN
...,...,...,...,...,...,...,...,...,...,...
4996,FIT5996,Arun,33.0,Male,13224.0,357.0,62.0,NaN,94.0,3.2
4997,FIT5997,Lakshmi,34.0,Male,12493.0,NaN,18.0,07-09-2035,120.0,4.2
4998,FIT5998,Kavya,48.0,Female,7945.0,109.0,40.0,08-09-2035,75.0,8.5
4999,FIT5999,NaN,24.0,Female,13793.0,710.0,65.0,09-09-2035,131.0,10.0
5000,FIT6000,NaN,23.0,Male,12654.0,720.0,75.0,04-09-2035,43.0,NaN

In [ ]:
df.head()

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours
0,FIT1000,Suresh,NaN,Female,15257.0,300.0,97.0,01-01-2022,NaN,7.8
1,FIT1001,Priya,30.0,Male,1570.0,119.0,NaN,02-01-2022,179.0,3.8
2,FIT1002,Arun,49.0,Male,15594.0,206.0,33.0,03-01-2022,133.0,4.0
3,FIT1003,Vikram,39.0,Female,4085.0,NaN,117.0,04-01-2022,95.0,NaN
4,FIT1004,Divya,23.0,Male,14407.0,969.0,56.0,05-01-2022,84.0,NaN

In [ ]:
df.tail()

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours
4996,FIT5996,Arun,33.0,Male,13224.0,357.0,62.0,NaN,94.0,3.2
4997,FIT5997,Lakshmi,34.0,Male,12493.0,NaN,18.0,07-09-2035,120.0,4.2
4998,FIT5998,Kavya,48.0,Female,7945.0,109.0,40.0,08-09-2035,75.0,8.5
4999,FIT5999,NaN,24.0,Female,13793.0,710.0,65.0,09-09-2035,131.0,10.0
5000,FIT6000,NaN,23.0,Male,12654.0,720.0,75.0,04-09-2035,43.0,NaN

In [ ]:
df.shape

(5001, 10)

In [ ]:
df.columns

Index(['User_ID', 'Name', 'Age', 'Gender', 'Steps', 'Calories_Burned',
       'Workout_Duration_Min', 'Date', 'Heart_Rate', 'Sleep_Hours'],
      dtype='object')

In [ ]:
df.dtypes

User_ID                  object
Name                     object
Age                     float64
Gender                   object
Steps                   float64
Calories_Burned         float64
Workout_Duration_Min    float64
Date                     object
Heart_Rate              float64
Sleep_Hours             float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User_ID               4501 non-null   object
 1   Name                  4500 non-null   object
 2   Age                   4501 non-null   float64
 3   Gender                4501 non-null   object
 4   Steps                 4501 non-null   float64
 5   Calories_Burned       4501 non-null   float64
 6   Workout_Duration_Min  4501 non-null   float64
 7   Date                  4501 non-null   object
 8   Heart_Rate            4501 non-null   float64
 9   Sleep_Hours           4500 non-null   float64
dtypes: float64(6), object(4)
memory usage: 390.8+ KB

In [ ]:
df.describe()

,Age,Steps,Calories_Burned,Workout_Duration_Min,Heart_Rate,Sleep_Hours
count,4501.000000,4501.000000,4501.000000,4501.000000,4501.000000,4500.000000
mean,41.036214,10443.373028,549.762275,64.829371,119.264164,6.512044
std,13.388395,5458.168131,258.651468,31.816694,34.948810,2.048222
min,18.000000,1002.000000,100.000000,10.000000,43.000000,3.000000
25%,30.000000,5719.000000,325.000000,37.000000,89.000000,4.700000
50%,41.000000,10417.000000,551.000000,65.000000,120.000000,6.500000
75%,52.000000,15246.000000,773.000000,92.000000,150.000000,8.300000
max,64.000000,19988.000000,999.000000,119.000000,179.000000,10.000000

In [ ]:
print( df["User_ID"].isnull().sum())

500

In [ ]:
df["User_ID"].fillna(method="ffill", inplace=True)
df["User_ID"].fillna(method="bfill", inplace=True)
df

/tmp/ipython-input-823088267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["User_ID"].fillna(method="ffill", inplace=True)
/tmp/ipython-input-823088267.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["User_ID"].fillna(method="ffill", inplace=True)
/tmp/ipython-input-823088267.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["User_ID"].fillna(method="bfill", inplace=True)

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours,City
0,FIT1000,Suresh,41,Female,15257,300,97,2022-01-01,121,7.8,New York
12,FIT1031,Karthik,40,Female,15087,731,95,2022-01-02,168,7.9,Los Angeles
24,FIT1059,Ramesh,58,Male,13877,551,103,2022-01-03,178,6.7,Chicago
36,FIT1090,Ramesh,46,Female,11087,438,73,2022-01-04,98,4.7,Houston
55,FIT1151,Divya,59,Female,4513,551,108,2022-01-06,176,6.9,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...
1719,FIT5849,Ramesh,30,Female,12603,232,25,2035-12-04,162,9.6,Houston
1728,FIT5879,Kavya,41,Male,15427,822,57,2035-12-05,123,7.3,Phoenix
1739,FIT5910,Unknown,59,Female,10417,918,10,2035-12-06,125,5.0,New York
1750,FIT5940,Karthik,32,Female,6712,354,49,2035-12-07,81,6.7,Los Angeles
1759,FIT5971,Lakshmi,48,Female,5711,878,28,2035-12-08,72,7.1,Chicago

In [ ]:
df["User_ID"].fillna(0, inplace=True)
df

/tmp/ipython-input-4044742473.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["User_ID"].fillna(0, inplace=True)

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours,City
0,FIT1000,Suresh,41,Female,15257,300,97,2022-01-01,121,7.8,New York
12,FIT1031,Karthik,40,Female,15087,731,95,2022-01-02,168,7.9,Los Angeles
24,FIT1059,Ramesh,58,Male,13877,551,103,2022-01-03,178,6.7,Chicago
36,FIT1090,Ramesh,46,Female,11087,438,73,2022-01-04,98,4.7,Houston
55,FIT1151,Divya,59,Female,4513,551,108,2022-01-06,176,6.9,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...
1719,FIT5849,Ramesh,30,Female,12603,232,25,2035-12-04,162,9.6,Houston
1728,FIT5879,Kavya,41,Male,15427,822,57,2035-12-05,123,7.3,Phoenix
1739,FIT5910,Unknown,59,Female,10417,918,10,2035-12-06,125,5.0,New York
1750,FIT5940,Karthik,32,Female,6712,354,49,2035-12-07,81,6.7,Los Angeles
1759,FIT5971,Lakshmi,48,Female,5711,878,28,2035-12-08,72,7.1,Chicago

In [ ]:
print(df["User_ID"].isnull().sum())

0

In [ ]:
df["Name"]=df["Name"].str.strip()
df

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours,City
0,FIT1000,Suresh,41,Female,15257,300,97,2022-01-01,121,7.8,New York
12,FIT1031,Karthik,40,Female,15087,731,95,2022-01-02,168,7.9,Los Angeles
24,FIT1059,Ramesh,58,Male,13877,551,103,2022-01-03,178,6.7,Chicago
36,FIT1090,Ramesh,46,Female,11087,438,73,2022-01-04,98,4.7,Houston
55,FIT1151,Divya,59,Female,4513,551,108,2022-01-06,176,6.9,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...
1719,FIT5849,Ramesh,30,Female,12603,232,25,2035-12-04,162,9.6,Houston
1728,FIT5879,Kavya,41,Male,15427,822,57,2035-12-05,123,7.3,Phoenix
1739,FIT5910,Unknown,59,Female,10417,918,10,2035-12-06,125,5.0,New York
1750,FIT5940,Karthik,32,Female,6712,354,49,2035-12-07,81,6.7,Los Angeles
1759,FIT5971,Lakshmi,48,Female,5711,878,28,2035-12-08,72,7.1,Chicago

In [ ]:
df["Name"]=df["Name"].str.title()

NameError: name 'df' is not defined

In [ ]:
df["Name"].fillna("Unknown",inplace=True)

/tmp/ipython-input-2160184949.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown",inplace=True)

In [ ]:
print(df["Name"])

0        Suresh
1         Priya
2          Arun
3        Vikram
4         Divya
         ...
4996       Arun
4997    Lakshmi
4998      Kavya
4999    Unknown
5000    Unknown
Name: Name, Length: 5001, dtype: object

In [ ]:
print( df["Name"].isnull().sum())

0

In [ ]:
df["Age"]=df["Age"].astype(float)

In [ ]:
df["Age"].fillna(df["Age"].median(),inplace=True)

/tmp/ipython-input-860536840.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

In [ ]:
df.loc[(df["Age"]<0),"Age"]=df["Age"].median()

In [ ]:
df.loc[(df["Age"]>120),"Age"]=df["Age"].median()

In [ ]:
df["Age"] = df["Age"].astype(int)

In [ ]:
print(df["Age"].describe())

count    5001.000000
mean       41.032593
std        12.701352
min        18.000000
25%        31.000000
50%        41.000000
75%        51.000000
max        64.000000
Name: Age, dtype: float64

In [ ]:
print( df["Age"].isnull().sum())

0

In [ ]:
df["Gender"]=df["Gender"].astype(str)

In [ ]:
df["Gender"]=df["Gender"].str.strip().str.capitalize()

In [ ]:
df["Gender"].fillna("Unknown",inplace=True)

/tmp/ipython-input-4079419841.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna("Unknown",inplace=True)

In [ ]:
print( df["Gender"].isnull().sum())

0

In [ ]:
df["Steps"] = df["Steps"].astype(float)

In [ ]:
df["Steps"].fillna(df["Steps"].median(), inplace=True)

/tmp/ipython-input-3160786177.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Steps"].fillna(df["Steps"].median(), inplace=True)

In [ ]:
df.loc[(df["Steps"] < 0),"Steps"]= df["Steps"].median()

In [ ]:
df.loc[(df["Steps"] > 1000000),"Steps"]= df["Steps"].median()

In [ ]:
df["Steps"] = df["Steps"].astype(int)

In [ ]:
print(df["Steps"].describe())

count     5001.000000
mean     10440.736253
std       5178.078989
min       1002.000000
25%       6256.000000
50%      10417.000000
75%      14555.000000
max      19988.000000
Name: Steps, dtype: float64

In [ ]:
print( df["Steps"].isnull().sum())

0

In [ ]:
df["Calories_Burned"] = df["Calories_Burned"].astype(float)

In [ ]:
df["Calories_Burned"].fillna(df["Calories_Burned"].median(), inplace=True)

/tmp/ipython-input-2391815721.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Calories_Burned"].fillna(df["Calories_Burned"].median(), inplace=True)

In [ ]:
df.loc[(df["Calories_Burned"] < 0) , "Calories_Burned"]=df["Calories_Burned"].median()

In [ ]:
df.loc[(df["Calories_Burned"] > 10000) , "Calories_Burned"]=df["Calories_Burned"].median()

In [ ]:
df["Calories_Burned"] = df["Calories_Burned"].astype(int)

In [ ]:
print(df["Calories_Burned"].describe())

count    5001.000000
mean      549.886023
std       245.378609
min       100.000000
25%       349.000000
50%       551.000000
75%       750.000000
max       999.000000
Name: Calories_Burned, dtype: float64

In [ ]:
print( df["Calories_Burned"].isnull().sum())

0

In [ ]:
df["Workout_Duration_Min"]=df["Workout_Duration_Min"].astype(float)

In [ ]:
df["Workout_Duration_Min"].fillna(df["Workout_Duration_Min"].median(), inplace=True)

/tmp/ipython-input-2295023151.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Workout_Duration_Min"].fillna(df["Workout_Duration_Min"].median(), inplace=True)

In [ ]:
df.loc[(df["Workout_Duration_Min"] < 0), "Workout_Duration_Min"]= df["Workout_Duration_Min"].median()

In [ ]:
df.loc[(df["Workout_Duration_Min"] > 1440), "Workout_Duration_Min"]= df["Workout_Duration_Min"].median()

In [ ]:
df["Workout_Duration_Min"] = df["Workout_Duration_Min"].astype(int)

In [ ]:
print(df["Workout_Duration_Min"].describe())

count    5001.000000
mean       64.846431
std        30.184009
min        10.000000
25%        40.000000
50%        65.000000
75%        89.000000
max       119.000000
Name: Workout_Duration_Min, dtype: float64

In [ ]:
print( df["Workout_Duration_Min"].isnull().sum())

0

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [ ]:
df.dropna(subset=["Date"], inplace=True)

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.sort_values(by="Date", inplace=True)

In [ ]:
print(df["Date"].head())

0    2022-01-01
12   2022-01-02
24   2022-01-03
36   2022-01-04
55   2022-01-06
Name: Date, dtype: datetime64[ns]

In [ ]:
print( df["Date"].isnull().sum())

0

In [ ]:
df["Heart_Rate"] = df["Heart_Rate"].astype(float)

In [ ]:
df["Heart_Rate"].fillna(df["Heart_Rate"].median(), inplace=True)

/tmp/ipython-input-1642609296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Heart_Rate"].fillna(df["Heart_Rate"].median(), inplace=True)

In [ ]:
df.loc[(df["Heart_Rate"] < 40) | (df["Heart_Rate"] > 220), "Heart_Rate"] = df["Heart_Rate"].median()

In [ ]:
df["Heart_Rate"] = df["Heart_Rate"].astype(int)

In [ ]:
print(df["Heart_Rate"].describe())

count    1768.000000
mean      119.978507
std        33.880121
min        43.000000
25%        91.000000
50%       121.000000
75%       148.000000
max       179.000000
Name: Heart_Rate, dtype: float64

In [ ]:
print( df["Heart_Rate"].isnull().sum())

0

In [ ]:
df["Sleep_Hours"] = df["Sleep_Hours"].astype(float)

In [ ]:
df["Sleep_Hours"].fillna(df["Sleep_Hours"].median(), inplace=True)

/tmp/ipython-input-3620286179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Sleep_Hours"].fillna(df["Sleep_Hours"].median(), inplace=True)

In [ ]:
df.loc[(df["Sleep_Hours"] < 0) | (df["Sleep_Hours"] > 24), "Sleep_Hours"] = df["Sleep_Hours"].median()

In [ ]:
df["Sleep_Hours"] = df["Sleep_Hours"].round(1)

In [ ]:
print(df["Sleep_Hours"].describe())

count    1768.000000
mean        6.629808
std         1.915481
min         3.000000
25%         5.100000
50%         6.700000
75%         8.200000
max        10.000000
Name: Sleep_Hours, dtype: float64

In [ ]:
print( df["Sleep_Hours"].isnull().sum())

0

In [ ]:
cities = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]

In [ ]:
df["City"] = [cities[i % len(cities)] for i in range(len(df))]

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.to_csv("/content/fitness_tracker.csv", index=False)

In [ ]:
print( df["City"].isnull().sum())

0

In [ ]:
df

,User_ID,Name,Age,Gender,Steps,Calories_Burned,Workout_Duration_Min,Date,Heart_Rate,Sleep_Hours,City
0,FIT1000,Suresh,41,Female,15257,300,97,2022-01-01,121,7.8,New York
12,FIT1031,Karthik,40,Female,15087,731,95,2022-01-02,168,7.9,Los Angeles
24,FIT1059,Ramesh,58,Male,13877,551,103,2022-01-03,178,6.7,Chicago
36,FIT1090,Ramesh,46,Female,11087,438,73,2022-01-04,98,4.7,Houston
55,FIT1151,Divya,59,Female,4513,551,108,2022-01-06,176,6.9,Phoenix
...,...,...,...,...,...,...,...,...,...,...,...
1719,FIT5849,Ramesh,30,Female,12603,232,25,2035-12-04,162,9.6,Houston
1728,FIT5879,Kavya,41,Male,15427,822,57,2035-12-05,123,7.3,Phoenix
1739,FIT5910,Unknown,59,Female,10417,918,10,2035-12-06,125,5.0,New York
1750,FIT5940,Karthik,32,Female,6712,354,49,2035-12-07,81,6.7,Los Angeles
1759,FIT5971,Lakshmi,48,Female,5711,878,28,2035-12-08,72,7.1,Chicago

In [ ]:
df.to_excel("cleaned_file.xlsx", index=False)


from google.colab import files
files.download("cleaned_file.xlsx")